# Team 7 - Garbage DumPY
## Demonstration of Basic Forward and Inverse Kinematics
### MANE 4120/6120 - Robotics 1 - Fall 2023

1. Import RPI Robotics Toolbox, Yahboom Jetson DOFBOT Code, etc.

In [1]:
import general_robotics_toolbox.general_robotics_toolbox as grt
import general_robotics_toolbox.general_robotics_toolbox_invkin as grt_ik
import Arm, Dofbot
from Arm_Lib import Arm_Device

import time
import numpy as np
import math
import path_generation
import move_read

start = np.array([90,90,90,90,90,15])
move_read.move_bot(start,disp=False)

In [6]:
num_steps = 10
q1 = np.array([90,65,22,70,90,15])
path = path_generation.gen_joint_space_path(start,q1,num_steps)
path_generation.path_follow(path,1,num_steps)


array([[  1. ,   4. ,  -4. ,   3. ,   5. , -25. ],
       [  0. ,  -1.5,  -2.8,  -1. ,   1. ,   0. ],
       [  1. ,  -1. ,  -1.6,  -1. ,   1. ,   1. ],
       [  1. ,  -1.5,  -2.4,  -1. ,   1. ,   1. ],
       [  0. ,  -1. ,  -2.2,  -1. ,   1. ,   1. ],
       [  0. ,  -1.5,  -3. ,  -1. ,   1. ,   1. ],
       [  0. ,  -1. ,  -1.8,  -1. ,   1. ,   0. ],
       [  0. ,  -1.5,  -2.6,  -1. ,   1. ,   0. ],
       [  0. ,  -1. ,  -2.4,  -1. ,   1. ,   0. ],
       [  0. ,  -0.5,  -1.2,  -1. ,   1. ,   0. ],
       [  0. ,  -1. ,  -2. ,  -1. ,   1. ,   0. ]])

In [7]:
q1 = np.array([45,100,80,100,100,90])
q2 = np.array([90,80,100,80,80,90])
q_res = move_read.move_bot(q1)
q_res2 = move_read.move_bot(q2)
print(q_res)
print(q_res2)

[ 45. 100.  80. 100.  99.  90.]
[ 88.  81. 100.  81.  80.  89.]


In [8]:
q1 = np.array([45,120,60,120,120,90])
q_res = move_read.move_bot(q1)
q2 = np.array([135,60,120,60,60,90])
q_des = path_generation.gen_joint_space_path(q_res, q2, 5)

for i in range(len(q_des)):
    move_read.move_bot(q_des[i])
    q_act = move_read.read_joints()

    error = q_des[i] - q_act
    print(error)

[ 1. -1.  1.  0.  0.  0.]
[ 0.8 -1.  -0.4 -1.  -0.8  0.2]
[ 0.6 -1.   0.2 -1.  -0.6  0.4]
[ 1.4 -1.  -0.2 -1.   0.6  0.6]
[ 1.2  0.   0.4 -1.  -0.2  0.8]
[ 1.  0.  0. -1.  0.  1.]


In [7]:
q1 = np.array([45,120,60,120,120,90])
q_res = move_read.move_bot(q1)
q2 = np.array([135,60,120,60,60,90])
steps = 10
time = 1
path = path_generation.gen_joint_space_path(q_res, q2,steps)
error = path_generation.path_follow(path,time,steps)
print(error)


[[ 0.          0.          1.          0.          0.         -1.        ]
 [ 5.         -4.77777778  1.44444444 -3.66666667 -1.55555556  0.11111111]
 [ 4.         -2.55555556  0.88888889 -2.33333333 -0.11111111  0.22222222]
 [ 3.         -3.33333333  0.33333333 -2.         -0.66666667  0.33333333]
 [ 3.         -3.11111111  0.77777778 -1.66666667 -1.22222222  0.44444444]
 [ 3.         -1.88888889  1.22222222 -2.33333333 -0.77777778  0.55555556]
 [ 4.         -2.66666667  1.66666667 -2.         -1.33333333  0.66666667]
 [ 4.         -2.44444444  1.11111111 -1.66666667 -0.88888889  0.77777778]
 [ 4.         -2.22222222  1.55555556 -2.33333333 -1.44444444  0.88888889]
 [ 4.         -2.          2.         -2.         -1.          1.        ]
 [ 4.         -2.77777778  1.44444444 -2.66666667 -0.55555556  1.11111111]]


In [5]:
q1 = np.array([45,120,60,120,120,90])
q_res = move_read.move_bot(q1)
q2 = np.array([135,60,120,60,60,90])

steps = 20
time = 2
kp = .1
ki = .1
kd = .01

path = path_generation.gen_joint_space_path(q_res, q2,steps)
error = path_generation.pid_path_follow(path,time,steps,kp,ki,kd)
print(error)

[0.21 0.   0.21 0.   0.   0.  ]
[ 0.6786 -0.4305 -0.0669 -0.42   -0.1995  0.0105]
[ 0.222106 -0.346905 -0.055949 -0.3282   -0.145395  0.018705]
[ 0.14466826 -0.10710505 -0.03962829 -0.081122   -0.11957795  0.02598305]
[ 0.33927679 -0.39557561  0.15814447 -0.36169762 -0.12402082  0.03387799]
[ 0.24683504 -0.19870547  0.09264839 -0.15613752 -0.13123131  0.04256795]
[ 0.37335419 -0.25047145 -0.15530161 -0.19852931 -0.13554143  0.05194213]
[ 0.47813574 -0.30151637  0.09310498 -0.23954898 -0.13853782  0.06196739]
[ 0.35222149 -0.32856392  0.06051235 -0.25590922 -0.14109146  0.0726547 ]
[ 0.2755827  -0.35165458  0.02075828 -0.26763839 -0.14321347  0.08401618]
[ 0.43560219 -0.3770845   0.00627432 -0.28102459 -0.14481464  0.09605991]
[ 0.54412599 -0.19413226 -0.00358433 -0.29533915 -0.14587082  0.10879311]
[ 0.41427006 -0.47794014 -0.0161435  -0.30981684 -0.14638065  0.1222233 ]
[ 0.5450892  -0.26927635  0.17916909 -0.32437909 -0.1463408   0.13635826]
[ 0.44768951 -0.31385556  0.11727922 -0.33